### ISSUE TITLE
redux-saga integration

### ISSUE THREAD

**Issue by scottc** [mtennoe/swagger-typescript-codegen#75]
I'm using swagger-typescript-codegen along side redux-saga.

For every swagger api I need to write some additional repetitive boilerplate code (action types, watcher generator functions and saga generator functions), to integrate the apis into my codebase.

It would be nice if this additional code was also generated for me.

It's beyond the scope of swagger-typescript-codegen, to have redux-saga integration.

I'm unsure if this can be achieved using the existing templates.

But it would be nice to have an extension, supplementary tool or documentation, that would help facilitate this.

**Comment by sbusch** [comment]
It should be possible by overriding the templates and changing them to your needs, but (in my experience):

1. Mustache template engine is quite limited, so it'll be not much fun :-)
2. Because of just three "big" templates, the maintenance of your templates after upstream changes could be a PITA (finer granularity with more, smaller templates would definitely help here, but we're not there yet, and Mustache is no help here, either)

Could you provide an example with Swagger def, the generated TS code and your hand-crafted boilerplate?

**Comment by mtennoe** [comment]
Yup, changing a custom template would work (we are doing this on a project I am working on). It does take some work to keep it up-to-date with the upstream default templates, but we have found that to be reasonable (and we oftentimes don't need to update the template either).

In addition to making the various templates smaller and more granular, we also have discussed replacing mustache templates with ES6 string templates, which could allow for smarter templates - that might make this easier in your case?

**Comment by scottc** [comment]
Closing, I'm no longer pursuing this.

The answer is either customizing the template.
Or adding ES6 string template support feature.
